version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    groups:
      dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
    ignore: [ ]
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    ignore-labels:
      - "skip-dependency-update"
    custom-labels:
      - dependency: "dependencies"
      - images:
          - "image-*"
    pull-request-title:
      format: "${{ type }}(${{ scope }}): ${{ subject }}"
